[build]
  functions = "functions"
  command = "npm run build && npm run bootstrap"
  publish = "dist/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"